OPENAI_API_KEY= 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
PINECONE_API_KEY= pcsk_xfzZn_DwWmrxmBn7eJv7c25CYJiB1Au1Q5dwhwfnAMcmZ4o9hj1T6EJ78sxQ5antartYh
PINECONE_ENVIRONMENT=us-east-1-aws
